//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  /** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  event: Event;
  eventConnection: EventConnection;
  testimonial: Testimonial;
  testimonialConnection: TestimonialConnection;
  siteImages: SiteImages;
  siteImagesConnection: SiteImagesConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEventArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEventConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EventFilter>;
};


export type QueryTestimonialArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTestimonialConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TestimonialFilter>;
};


export type QuerySiteImagesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteImagesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteImagesFilter>;
};

export type DocumentFilter = {
  event?: InputMaybe<EventFilter>;
  testimonial?: InputMaybe<TestimonialFilter>;
  siteImages?: InputMaybe<SiteImagesFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Event | Testimonial | SiteImages | Folder;

export type Event = Node & Document & {
  __typename?: 'Event';
  day: Scalars['String']['output'];
  monthLabel: Scalars['String']['output'];
  titleIt: Scalars['String']['output'];
  titleEn: Scalars['String']['output'];
  venue: Scalars['String']['output'];
  ticketUrl: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type EventFilter = {
  day?: InputMaybe<StringFilter>;
  monthLabel?: InputMaybe<StringFilter>;
  titleIt?: InputMaybe<StringFilter>;
  titleEn?: InputMaybe<StringFilter>;
  venue?: InputMaybe<StringFilter>;
  ticketUrl?: InputMaybe<StringFilter>;
};

export type EventConnectionEdges = {
  __typename?: 'EventConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Event>;
};

export type EventConnection = Connection & {
  __typename?: 'EventConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<EventConnectionEdges>>>;
};

export type Testimonial = Node & Document & {
  __typename?: 'Testimonial';
  quote: Scalars['String']['output'];
  author: Scalars['String']['output'];
  rating: Scalars['Float']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type TestimonialFilter = {
  quote?: InputMaybe<StringFilter>;
  author?: InputMaybe<StringFilter>;
  rating?: InputMaybe<NumberFilter>;
};

export type TestimonialConnectionEdges = {
  __typename?: 'TestimonialConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Testimonial>;
};

export type TestimonialConnection = Connection & {
  __typename?: 'TestimonialConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TestimonialConnectionEdges>>>;
};

export type SiteImages = Node & Document & {
  __typename?: 'SiteImages';
  heroPoster?: Maybe<Scalars['String']['output']>;
  homeStory?: Maybe<Scalars['String']['output']>;
  experienceBody?: Maybe<Scalars['String']['output']>;
  experienceMusic?: Maybe<Scalars['String']['output']>;
  aboutStory?: Maybe<Scalars['String']['output']>;
  aboutEarthpercentBadge?: Maybe<Scalars['String']['output']>;
  eventsLocation?: Maybe<Scalars['String']['output']>;
  eventsFirstTime?: Maybe<Scalars['String']['output']>;
  blogCoverPillar?: Maybe<Scalars['String']['output']>;
  blogCoverHome?: Maybe<Scalars['String']['output']>;
  blogCoverPlanet?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SiteImagesFilter = {
  heroPoster?: InputMaybe<ImageFilter>;
  homeStory?: InputMaybe<ImageFilter>;
  experienceBody?: InputMaybe<ImageFilter>;
  experienceMusic?: InputMaybe<ImageFilter>;
  aboutStory?: InputMaybe<ImageFilter>;
  aboutEarthpercentBadge?: InputMaybe<ImageFilter>;
  eventsLocation?: InputMaybe<ImageFilter>;
  eventsFirstTime?: InputMaybe<ImageFilter>;
  blogCoverPillar?: InputMaybe<ImageFilter>;
  blogCoverHome?: InputMaybe<ImageFilter>;
  blogCoverPlanet?: InputMaybe<ImageFilter>;
};

export type SiteImagesConnectionEdges = {
  __typename?: 'SiteImagesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<SiteImages>;
};

export type SiteImagesConnection = Connection & {
  __typename?: 'SiteImagesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteImagesConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateEvent: Event;
  createEvent: Event;
  updateTestimonial: Testimonial;
  createTestimonial: Testimonial;
  updateSiteImages: SiteImages;
  createSiteImages: SiteImages;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateEventArgs = {
  relativePath: Scalars['String']['input'];
  params: EventMutation;
};


export type MutationCreateEventArgs = {
  relativePath: Scalars['String']['input'];
  params: EventMutation;
};


export type MutationUpdateTestimonialArgs = {
  relativePath: Scalars['String']['input'];
  params: TestimonialMutation;
};


export type MutationCreateTestimonialArgs = {
  relativePath: Scalars['String']['input'];
  params: TestimonialMutation;
};


export type MutationUpdateSiteImagesArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteImagesMutation;
};


export type MutationCreateSiteImagesArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteImagesMutation;
};

export type DocumentUpdateMutation = {
  event?: InputMaybe<EventMutation>;
  testimonial?: InputMaybe<TestimonialMutation>;
  siteImages?: InputMaybe<SiteImagesMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  event?: InputMaybe<EventMutation>;
  testimonial?: InputMaybe<TestimonialMutation>;
  siteImages?: InputMaybe<SiteImagesMutation>;
};

export type EventMutation = {
  day?: InputMaybe<Scalars['String']['input']>;
  monthLabel?: InputMaybe<Scalars['String']['input']>;
  titleIt?: InputMaybe<Scalars['String']['input']>;
  titleEn?: InputMaybe<Scalars['String']['input']>;
  venue?: InputMaybe<Scalars['String']['input']>;
  ticketUrl?: InputMaybe<Scalars['String']['input']>;
};

export type TestimonialMutation = {
  quote?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  rating?: InputMaybe<Scalars['Float']['input']>;
};

export type SiteImagesMutation = {
  heroPoster?: InputMaybe<Scalars['String']['input']>;
  homeStory?: InputMaybe<Scalars['String']['input']>;
  experienceBody?: InputMaybe<Scalars['String']['input']>;
  experienceMusic?: InputMaybe<Scalars['String']['input']>;
  aboutStory?: InputMaybe<Scalars['String']['input']>;
  aboutEarthpercentBadge?: InputMaybe<Scalars['String']['input']>;
  eventsLocation?: InputMaybe<Scalars['String']['input']>;
  eventsFirstTime?: InputMaybe<Scalars['String']['input']>;
  blogCoverPillar?: InputMaybe<Scalars['String']['input']>;
  blogCoverHome?: InputMaybe<Scalars['String']['input']>;
  blogCoverPlanet?: InputMaybe<Scalars['String']['input']>;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type EventFilter = {
  day?: StringFilter | null | undefined;
  monthLabel?: StringFilter | null | undefined;
  titleIt?: StringFilter | null | undefined;
  titleEn?: StringFilter | null | undefined;
  venue?: StringFilter | null | undefined;
  ticketUrl?: StringFilter | null | undefined;
};

export type NumberFilter = {
  lt?: number | null | undefined;
  lte?: number | null | undefined;
  gte?: number | null | undefined;
  gt?: number | null | undefined;
  eq?: number | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<number | null | undefined> | null | undefined;
};

export type TestimonialFilter = {
  quote?: StringFilter | null | undefined;
  author?: StringFilter | null | undefined;
  rating?: NumberFilter | null | undefined;
};

export type ImageFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type SiteImagesFilter = {
  heroPoster?: ImageFilter | null | undefined;
  homeStory?: ImageFilter | null | undefined;
  experienceBody?: ImageFilter | null | undefined;
  experienceMusic?: ImageFilter | null | undefined;
  aboutStory?: ImageFilter | null | undefined;
  aboutEarthpercentBadge?: ImageFilter | null | undefined;
  eventsLocation?: ImageFilter | null | undefined;
  eventsFirstTime?: ImageFilter | null | undefined;
  blogCoverPillar?: ImageFilter | null | undefined;
  blogCoverHome?: ImageFilter | null | undefined;
  blogCoverPlanet?: ImageFilter | null | undefined;
};

export type EventPartsFragment = { __typename: 'Event', day: string, monthLabel: string, titleIt: string, titleEn: string, venue: string, ticketUrl: string };

export type TestimonialPartsFragment = { __typename: 'Testimonial', quote: string, author: string, rating: number };

export type SiteImagesPartsFragment = { __typename: 'SiteImages', heroPoster: string | null, homeStory: string | null, experienceBody: string | null, experienceMusic: string | null, aboutStory: string | null, aboutEarthpercentBadge: string | null, eventsLocation: string | null, eventsFirstTime: string | null, blogCoverPillar: string | null, blogCoverHome: string | null, blogCoverPlanet: string | null };

export type EventQueryVariables = Exact<{
  relativePath: string;
}>;


export type EventQuery = { event: { __typename: 'Event', id: string, day: string, monthLabel: string, titleIt: string, titleEn: string, venue: string, ticketUrl: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type EventConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: EventFilter | null | undefined;
}>;


export type EventConnectionQuery = { eventConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Event', id: string, day: string, monthLabel: string, titleIt: string, titleEn: string, venue: string, ticketUrl: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type TestimonialQueryVariables = Exact<{
  relativePath: string;
}>;


export type TestimonialQuery = { testimonial: { __typename: 'Testimonial', id: string, quote: string, author: string, rating: number, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TestimonialConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: TestimonialFilter | null | undefined;
}>;


export type TestimonialConnectionQuery = { testimonialConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Testimonial', id: string, quote: string, author: string, rating: number, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type SiteImagesQueryVariables = Exact<{
  relativePath: string;
}>;


export type SiteImagesQuery = { siteImages: { __typename: 'SiteImages', id: string, heroPoster: string | null, homeStory: string | null, experienceBody: string | null, experienceMusic: string | null, aboutStory: string | null, aboutEarthpercentBadge: string | null, eventsLocation: string | null, eventsFirstTime: string | null, blogCoverPillar: string | null, blogCoverHome: string | null, blogCoverPlanet: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SiteImagesConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: SiteImagesFilter | null | undefined;
}>;


export type SiteImagesConnectionQuery = { siteImagesConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'SiteImages', id: string, heroPoster: string | null, homeStory: string | null, experienceBody: string | null, experienceMusic: string | null, aboutStory: string | null, aboutEarthpercentBadge: string | null, eventsLocation: string | null, eventsFirstTime: string | null, blogCoverPillar: string | null, blogCoverHome: string | null, blogCoverPlanet: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const EventPartsFragmentDoc = gql`
    fragment EventParts on Event {
  __typename
  day
  monthLabel
  titleIt
  titleEn
  venue
  ticketUrl
}
    `;
export const TestimonialPartsFragmentDoc = gql`
    fragment TestimonialParts on Testimonial {
  __typename
  quote
  author
  rating
}
    `;
export const SiteImagesPartsFragmentDoc = gql`
    fragment SiteImagesParts on SiteImages {
  __typename
  heroPoster
  homeStory
  experienceBody
  experienceMusic
  aboutStory
  aboutEarthpercentBadge
  eventsLocation
  eventsFirstTime
  blogCoverPillar
  blogCoverHome
  blogCoverPlanet
}
    `;
export const EventDocument = gql`
    query event($relativePath: String!) {
  event(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...EventParts
  }
}
    ${EventPartsFragmentDoc}`;
export const EventConnectionDocument = gql`
    query eventConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: EventFilter) {
  eventConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EventParts
      }
    }
  }
}
    ${EventPartsFragmentDoc}`;
export const TestimonialDocument = gql`
    query testimonial($relativePath: String!) {
  testimonial(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TestimonialParts
  }
}
    ${TestimonialPartsFragmentDoc}`;
export const TestimonialConnectionDocument = gql`
    query testimonialConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TestimonialFilter) {
  testimonialConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TestimonialParts
      }
    }
  }
}
    ${TestimonialPartsFragmentDoc}`;
export const SiteImagesDocument = gql`
    query siteImages($relativePath: String!) {
  siteImages(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteImagesParts
  }
}
    ${SiteImagesPartsFragmentDoc}`;
export const SiteImagesConnectionDocument = gql`
    query siteImagesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteImagesFilter) {
  siteImagesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteImagesParts
      }
    }
  }
}
    ${SiteImagesPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      event(variables: EventQueryVariables, options?: C): Promise<{data: EventQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventQueryVariables, query: string}> {
        return requester<{data: EventQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventQueryVariables, query: string}, EventQueryVariables>(EventDocument, variables, options);
      },
    eventConnection(variables?: EventConnectionQueryVariables, options?: C): Promise<{data: EventConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventConnectionQueryVariables, query: string}> {
        return requester<{data: EventConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventConnectionQueryVariables, query: string}, EventConnectionQueryVariables>(EventConnectionDocument, variables, options);
      },
    testimonial(variables: TestimonialQueryVariables, options?: C): Promise<{data: TestimonialQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialQueryVariables, query: string}> {
        return requester<{data: TestimonialQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialQueryVariables, query: string}, TestimonialQueryVariables>(TestimonialDocument, variables, options);
      },
    testimonialConnection(variables?: TestimonialConnectionQueryVariables, options?: C): Promise<{data: TestimonialConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialConnectionQueryVariables, query: string}> {
        return requester<{data: TestimonialConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialConnectionQueryVariables, query: string}, TestimonialConnectionQueryVariables>(TestimonialConnectionDocument, variables, options);
      },
    siteImages(variables: SiteImagesQueryVariables, options?: C): Promise<{data: SiteImagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteImagesQueryVariables, query: string}> {
        return requester<{data: SiteImagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteImagesQueryVariables, query: string}, SiteImagesQueryVariables>(SiteImagesDocument, variables, options);
      },
    siteImagesConnection(variables?: SiteImagesConnectionQueryVariables, options?: C): Promise<{data: SiteImagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteImagesConnectionQueryVariables, query: string}> {
        return requester<{data: SiteImagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteImagesConnectionQueryVariables, query: string}, SiteImagesConnectionQueryVariables>(SiteImagesConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  